(* Generated by ocaml-tree-sitter. *)
(*
   powershell grammar

   entrypoint: program
*)

open! Sexplib.Conv
open Tree_sitter_run

type simple_name = Token.t (* pattern [a-zA-Z_][a-zA-Z0-9_]* *)

type command_token = Token.t

type pat_brk_ = Token.t (* pattern [bB][rR][eE][aA][kK][--] *)

type pat__crep = Token.t (* pattern [--][cC][rR][eE][pP][lL][aA][cC][eE] *)

type pat__lt = Token.t (* pattern [--][lL][tT] *)

type pat_throw_ = Token.t (* pattern [tT][hH][rR][oO][wW][--] *)

type pat__isplit = Token.t (* pattern [--][iI][sS][pP][lL][iI][tT] *)

type pat_catch = Token.t (* pattern [cC][aA][tT][cC][hH] *)

type imm_tok_squotsquot = Token.t (* "''" *)

type merging_redirection_operator = [
    `STARGTAMP1 of Token.t (* "*>&1" *)
  | `X_2GTAMP1 of Token.t (* "2>&1" *)
  | `X_3GTAMP1 of Token.t (* "3>&1" *)
  | `X_4GTAMP1 of Token.t (* "4>&1" *)
  | `X_5GTAMP1 of Token.t (* "5>&1" *)
  | `X_6GTAMP1 of Token.t (* "6>&1" *)
  | `STARGTAMP2 of Token.t (* "*>&2" *)
  | `X_1GTAMP2 of Token.t (* "1>&2" *)
  | `X_3GTAMP2 of Token.t (* "3>&2" *)
  | `X_4GTAMP2 of Token.t (* "4>&2" *)
  | `X_5GTAMP2 of Token.t (* "5>&2" *)
  | `X_6GTAMP2 of Token.t (* "6>&2" *)
]

type tok_dollar_choice_choice_prec_p1_pat_0705c16_colon_pat_ae6f473 = Token.t

type verbatim_string_characters = Token.t

type pat__band = Token.t (* pattern [--][bB][aA][nN][dD] *)

type pat__isnot = Token.t (* pattern [--][iI][sS][nN][oO][tT] *)

type tok_prec_p1_pat_class = Token.t

type pat__is = Token.t (* pattern [--][iI][sS] *)

type pat__le = Token.t (* pattern [--][lL][eE] *)

type pat__not = Token.t (* pattern [--][nN][oO][tT] *)

type pat_filter_ = Token.t (* pattern [fF][iI][lL][tT][eE][rR][--] *)

type command_argument_sep = [
    `Rep1_SPACE of Token.t (* " " *) list (* one or more *)
  | `COLON of Token.t (* ":" *)
]

type pat__eq = Token.t (* pattern [--][eE][qQ] *)

type pat_cont_ = Token.t (* pattern [cC][oO][nN][tT][iI][nN][uU][eE][--] *)

type pat__ieq = Token.t (* pattern [--][iI][eE][qQ] *)

type real_literal = Token.t

type pat_71f01fd = Token.t (* pattern &[^&]* *)

type pat__contas = Token.t (* pattern [--][cC][oO][nN][tT][aA][iI][nN][sS] *)

type pat_switch_ = Token.t (* pattern [sS][wW][iI][tT][cC][hH][--] *)

type generic_token = Token.t

type pat__shr = Token.t (* pattern [--][sS][hH][rR] *)

type pat_enum_ = Token.t (* pattern [eE][nN][uU][mM][--] *)

type pat__irep = Token.t (* pattern [--][iI][rR][eE][pP][lL][aA][cC][eE] *)

type pat_trap_ = Token.t (* pattern [tT][rR][aA][pP][--] *)

type pat__cge = Token.t (* pattern [--][cC][gG][eE] *)

type pat_if = Token.t (* pattern [iI][fF] *)

type pat_ret = Token.t (* pattern [rR][eE][tT][uU][rR][nN] *)

type pat__in = Token.t (* pattern [--][iI][nN] *)

type imm_tok_pat_8a0ae06 = Token.t (* pattern `.{1}|`\r?\n *)

type pat_4f029d2 = Token.t (* pattern "\"[^\"]*\"" *)

type pat__cnotcs =
  Token.t (* pattern [--][cC][nN][oO][tT][cC][oO][nN][tT][aA][iI][nN][sS] *)

type pat__wild = Token.t (* pattern [--][wW][iI][lL][dD][cC][aA][rR][dD] *)

type pat__regex = Token.t (* pattern [--][rR][eE][gG][eE][xX] *)

type pat_end = Token.t (* pattern [eE][nN][dD] *)

type anon_choice_PLUS_da42005 = [
    `PLUS of Token.t (* "+" *)
  | `DASH of Token.t (* "-" *)
]

type pat__csplit = Token.t (* pattern [--][cC][sS][pP][lL][iI][tT] *)

type pat_brk = Token.t (* pattern [bB][rR][eE][aA][kK] *)

type dimension = Token.t (* "," *) list (* one or more *)

type pat__cnot_ =
  Token.t (* pattern [--][cC][nN][oO][tT][mM][aA][tT][cC][hH] *)

type pat__cgt = Token.t (* pattern [--][cC][gG][tT] *)

type pat_proc = Token.t (* pattern [pP][rR][oO][cC][eE][sS][sS] *)

type anon_choice_SLASH_4ca1f7c = [
    `SLASH of Token.t (* "/" *)
  | `BSLASH of Token.t (* "\\" *)
  | `PERC of Token.t (* "%" *)
  | `STAR of Token.t (* "*" *)
]

type pat_d72a25c = Token.t (* pattern [^\|\r\n]+ *)

type command_invokation_operator = [
    `DOT of Token.t (* "." *)
  | `AMP of Token.t (* "&" *)
]

type pat__ilt = Token.t (* pattern [--][iI][lL][tT] *)

type pat__match = Token.t (* pattern [--][mM][aA][tT][cC][hH] *)

type tok_prec_p1_pat_enum = Token.t

type pat_trap = Token.t (* pattern [tT][rR][aA][pP] *)

type imm_tok_dquot = Token.t (* "\"" *)

type pat__cnot = Token.t (* pattern [--][cC][nN][oO][tT][lL][iI][kK][eE] *)

type pat_class_ = Token.t (* pattern [cC][lL][aA][sS][sS][--] *)

type pat_75780b9 = Token.t (* pattern \$`(.{1}|`\r?\n) *)

type pat__ceq = Token.t (* pattern [--][cC][eE][qQ] *)

type pat_para = Token.t (* pattern [pP][aA][rR][aA][lL][lL][eE][lL] *)

type pat__split = Token.t (* pattern [--][sS][pP][lL][iI][tT] *)

type pat__file = Token.t (* pattern [--][fF][iI][lL][eE] *)

type pat__inotcs =
  Token.t (* pattern [--][iI][nN][oO][tT][cC][oO][nN][tT][aA][iI][nN][sS] *)

type pat__inot = Token.t (* pattern [--][iI][nN][oO][tT][lL][iI][kK][eE] *)

type pat__join = Token.t (* pattern [--][jJ][oO][iI][nN] *)

type pat_data = Token.t (* pattern [dD][aA][tT][aA] *)

type pat__bnot = Token.t (* pattern [--][bB][nN][oO][tT] *)

type label = Token.t

type pat__like = Token.t (* pattern [--][lL][iI][kK][eE] *)

type pat_fina = Token.t (* pattern [fF][iI][nN][aA][lL][lL][yY] *)

type tok_prec_p1_pat_static = Token.t

type pat__xor = Token.t (* pattern [--][xX][oO][rR] *)

type pat_exit_ = Token.t (* pattern [eE][xX][iI][tT][--] *)

type command_parameter = Token.t

type pat__ige = Token.t (* pattern [--][iI][gG][eE] *)

type pat_while = Token.t (* pattern [wW][hH][iI][lL][eE] *)

type imm_tok_pat_0f818ff = Token.t (* pattern "(\\r?\\n)+\\\"[^@]" *)

type verbatim_here_string_characters = Token.t

type pat__cconts =
  Token.t (* pattern [--][cC][cC][oO][nN][tT][aA][iI][nN][sS] *)

type pat_60937fc = Token.t (* pattern "@\\\" *\\r?\\n" *)

type pat__para = Token.t (* pattern [--][pP][aA][rR][aA][lL][lL][eE][lL] *)

type pat_cont = Token.t (* pattern [cC][oO][nN][tT][iI][nN][uU][eE] *)

type pat__ne = Token.t (* pattern [--][nN][eE] *)

type type_identifier = Token.t (* pattern [a-zA-Z0-9_]+ *)

type pat__and = Token.t (* pattern [--][aA][nN][dD] *)

type pat_func = Token.t (* pattern [fF][uU][nN][cC][tT][iI][oO][nN] *)

type pat_8a0ae06 = Token.t (* pattern `.{1}|`\r?\n *)

type pat_throw = Token.t (* pattern [tT][hH][rR][oO][wW] *)

type tok_at_choice_choice_prec_p1_pat_0705c16_colon_pat_ae6f473 = Token.t

type pat_ret_ = Token.t (* pattern [rR][eE][tT][uU][rR][nN][--] *)

type assignement_operator = [
    `EQ of Token.t (* "=" *)
  | `BANGEQ of Token.t (* "!=" *)
  | `PLUSEQ of Token.t (* "+=" *)
  | `STAREQ of Token.t (* "*=" *)
  | `SLASHEQ of Token.t (* "/=" *)
  | `PERCEQ of Token.t (* "%=" *)
  | `DASHEQ of Token.t (* "-=" *)
]

type pat_inli =
  Token.t (* pattern [iI][nN][lL][iI][nN][eE][sS][cC][rR][iI][pP][tT] *)

type pat_exit = Token.t (* pattern [eE][xX][iI][tT] *)

type pat_filter = Token.t (* pattern [fF][iI][lL][tT][eE][rR] *)

type pat__or = Token.t (* pattern [--][oO][rR] *)

type pat_dyna =
  Token.t (* pattern [dD][yY][nN][aA][mM][iI][cC][pP][aA][rR][aA][mM] *)

type file_redirection_operator = [
    `GT of Token.t (* ">" *)
  | `GTGT of Token.t (* ">>" *)
  | `X_2GT of Token.t (* "2>" *)
  | `X_2GTGT of Token.t (* "2>>" *)
  | `X_3GT of Token.t (* "3>" *)
  | `X_3GTGT of Token.t (* "3>>" *)
  | `X_4GT of Token.t (* "4>" *)
  | `X_4GTGT of Token.t (* "4>>" *)
  | `X_5GT of Token.t (* "5>" *)
  | `X_5GTGT of Token.t (* "5>>" *)
  | `X_6GT of Token.t (* "6>" *)
  | `X_6GTGT of Token.t (* "6>>" *)
  | `STARGT of Token.t (* "*>" *)
  | `STARGTGT of Token.t (* "*>>" *)
  | `LT of Token.t (* "<" *)
]

type pat_in = Token.t (* pattern [iI][nN] *)

type pat_func_ = Token.t (* pattern [fF][uU][nN][cC][tT][iI][oO][nN][--] *)

type pat_para_ = Token.t (* pattern [pP][aA][rR][aA][lL][lL][eE][lL][--] *)

type imm_tok_pat_0c51e85 =
  Token.t (* pattern "[^\\{\\}\\(\\);,\\|\\&\"'\\s\\r\\n]+" *)

type pat__as = Token.t (* pattern [--][aA][sS] *)

type pat_param = Token.t (* pattern [pP][aA][rR][aA][mM] *)

type pat__gt = Token.t (* pattern [--][gG][tT] *)

type pat__notin = Token.t (* pattern [--][nN][oO][tT][iI][nN] *)

type pat_else = Token.t (* pattern [eE][lL][sS][eE] *)

type pat_8310886 =
  Token.t (* pattern "[^\\{\\}\\(\\);,\\|\\&`\"'\\s\\r\\n\\[\\]\\+\\-\\*\\/\\$@<\\!]+" *)

type pat__f = Token.t (* pattern [--][fF] *)

type pat_try_ = Token.t (* pattern [tT][rR][yY][--] *)

type statement_terminator = Token.t

type pat_until = Token.t (* pattern [uU][nN][tT][iI][lL] *)

type imm_tok_dollar = Token.t (* "$" *)

type pat__cmatch = Token.t (* pattern [--][cC][mM][aA][tT][cC][hH] *)

type pat__notcos =
  Token.t (* pattern [--][nN][oO][tT][cC][oO][nN][tT][aA][iI][nN][sS] *)

type pipeline_chain_tail = [
    `AMPAMP of Token.t (* "&&" *)
  | `BARBAR of Token.t (* "||" *)
]

type pat__cne = Token.t (* pattern [--][cC][nN][eE] *)

type pat__supp =
  Token.t (* pattern [--][sS][uU][pP][pP][oO][rR][tT][eE][dD][cC][oO][mM][mM][aA][nN][dD] *)

type imm_tok_prec_p1_pat_5b7d8c6 =
  Token.t (* pattern [..][fF][oO][rR][eE][aA][cC][hH] *)

type pat_try = Token.t (* pattern [tT][rR][yY] *)

type pat_begin = Token.t (* pattern [bB][eE][gG][iI][nN] *)

type pat_elseif = Token.t (* pattern [eE][lL][sS][eE][iI][fF] *)

type pat_for = Token.t (* pattern [fF][oO][rR] *)

type pat__cle = Token.t (* pattern [--][cC][lL][eE] *)

type decimal_integer_literal = Token.t

type pat_while_ = Token.t (* pattern [wW][hH][iI][lL][eE][--] *)

type pat_0f43aa8 = Token.t (* pattern "\\\"(\\s*\\#*\
  )*" *)

type pat_for_ = Token.t (* pattern [fF][oO][rR][--] *)

type pat__bxor = Token.t (* pattern [--][bB][xX][oO][rR] *)

type tok_prec_p1_pat_hidden = Token.t

type imm_tok_pat_f92c05a = Token.t (* pattern \$(`.{1}|`\r?\n|[\s\\]) *)

type pat__clt = Token.t (* pattern [--][cC][lL][tT] *)

type imm_tok_pat_883ef26 = Token.t (* pattern "(\\r?\\n)+[^\\\"\\r\\n]" *)

type pat__igt = Token.t (* pattern [--][iI][gG][tT] *)

type pat__shl = Token.t (* pattern [--][sS][hH][lL] *)

type stop_parsing = Token.t (* pattern --%[^\r\n]* *)

type pat__ine = Token.t (* pattern [--][iI][nN][eE] *)

type pat_seq = Token.t (* pattern [sS][eE][qQ][uU][eE][nN][cC][eE] *)

type pat_switch = Token.t (* pattern [sS][wW][iI][tT][cC][hH] *)

type pat__clike = Token.t (* pattern [--][cC][lL][iI][kK][eE] *)

type pat__inot_ =
  Token.t (* pattern [--][iI][nN][oO][tT][mM][aA][tT][cC][hH] *)

type pat__notl = Token.t (* pattern [--][nN][oO][tT][lL][iI][kK][eE] *)

type hexadecimal_integer_literal = Token.t

type imm_tok_dquotdquot = Token.t (* "\"\"" *)

type pat__bor = Token.t (* pattern [--][bB][oO][rR] *)

type pat__ilike = Token.t (* pattern [--][iI][lL][iI][kK][eE] *)

type pat__repl = Token.t (* pattern [--][rR][eE][pP][lL][aA][cC][eE] *)

type pat_work_ = Token.t (* pattern [wW][oO][rR][kK][fF][lL][oO][wW][--] *)

type imm_tok_pat_3dc846d = Token.t (* pattern "(\\r?\\n)+\\\"@" *)

type pat__imatch = Token.t (* pattern [--][iI][mM][aA][tT][cC][hH] *)

type pat_fore = Token.t (* pattern [fF][oO][rR][eE][aA][cC][hH] *)

type pat__ile = Token.t (* pattern [--][iI][lL][eE] *)

type pat__notm = Token.t (* pattern [--][nN][oO][tT][mM][aA][tT][cC][hH] *)

type braced_variable = Token.t (* pattern \$\{[^}]+\} *)

type imm_tok_pat_46ba992 = Token.t (* pattern "[^\\$\\\"`]+" *)

type pat_do = Token.t (* pattern [dD][oO] *)

type imm_tok_pat_b45f689 = Token.t (* pattern [^\$\r\n`]+ *)

type pat_if_ = Token.t (* pattern [iI][fF][--] *)

type path_command_name_token = Token.t (* pattern [0-9a-zA-Z_?\-\.\\]+ *)

type imm_tok_pat_0da7e88 = Token.t (* pattern "(\\s*\\#*\
  )*\\\"" *)

type pat__case =
  Token.t (* pattern [--][cC][aA][sS][eE][sS][eE][nN][sS][iI][tT][iI][vV][eE] *)

type pat__exact = Token.t (* pattern [--][eE][xX][aA][cC][tT] *)

type pat__iconts =
  Token.t (* pattern [--][iI][cC][oO][nN][tT][aA][iI][nN][sS] *)

type imm_tok_dot = Token.t (* "." *)

type pat_work = Token.t (* pattern [wW][oO][rR][kK][fF][lL][oO][wW] *)

type pat_a8fb427 = Token.t (* pattern "[^\\$\"`]+" *)

type imm_tok_pat_509ec78 = Token.t (* pattern \r?\n *)

type pat__ge = Token.t (* pattern [--][gG][eE] *)

type verbatim_command_argument_chars =
  [
      `Pat_4f029d2 of pat_4f029d2
    | `Pat_71f01fd of pat_71f01fd
    | `Pat_d72a25c of pat_d72a25c
  ]
    list (* one or more *)

type foreach_parameter = [ `Pat__para of pat__para ]

type type_name = [
    `Type_id of type_identifier (*tok*)
  | `Type_name_DOT_type_id of (
        type_name * Token.t (* "." *) * type_identifier (*tok*)
    )
]

type anon_choice_pat__and_bad5cfe = [
    `Pat__and of pat__and
  | `Pat__or of pat__or
  | `Pat__xor of pat__xor
]

type format_operator = pat__f

type block_name = [
    `Pat_dyna of pat_dyna
  | `Pat_begin of pat_begin
  | `Pat_proc of pat_proc
  | `Pat_end of pat_end
]

type class_attribute = [
    `Tok_prec_p1_pat_hidden of tok_prec_p1_pat_hidden (*tok*)
  | `Tok_prec_p1_pat_static of tok_prec_p1_pat_static (*tok*)
]

type integer_literal = [
    `Deci_int_lit of decimal_integer_literal (*tok*)
  | `Hexa_int_lit of hexadecimal_integer_literal (*tok*)
]

type variable = [
    `DOLLARDOLLAR of Token.t (* "$$" *)
  | `DOLLARHAT of Token.t (* "$^" *)
  | `DOLLARQMARK of Token.t (* "$?" *)
  | `DOLLAR_ of Token.t (* "$_" *)
  | `Tok_dollar_choice_choice_prec_p1_pat_0705c16_colon_pat_ae6f473 of
      tok_dollar_choice_choice_prec_p1_pat_0705c16_colon_pat_ae6f473
  | `Tok_at_choice_choice_prec_p1_pat_0705c16_colon_pat_ae6f473 of
      tok_at_choice_choice_prec_p1_pat_0705c16_colon_pat_ae6f473
  | `Braced_var of braced_variable (*tok*)
]

type switch_parameter = [
    `Pat__regex of pat__regex
  | `Pat__wild of pat__wild
  | `Pat__exact of pat__exact
  | `Pat__case of pat__case
  | `Pat__para of pat__para
]

type anon_choice_SEMI_fddb21e = [
    `SEMI of Token.t (* ";" *)
  | `Imm_tok_pat_509ec78 of imm_tok_pat_509ec78
]

type comparison_operator = [
    `Pat__as of pat__as
  | `Pat__cconts of pat__cconts
  | `Pat__ceq of pat__ceq
  | `Pat__cge of pat__cge
  | `Pat__cgt of pat__cgt
  | `Pat__cle of pat__cle
  | `Pat__clike of pat__clike
  | `Pat__clt of pat__clt
  | `Pat__cmatch of pat__cmatch
  | `Pat__cne of pat__cne
  | `Pat__cnotcs of pat__cnotcs
  | `Pat__cnot of pat__cnot
  | `Pat__cnot_ of pat__cnot_
  | `Pat__contas of pat__contas
  | `Pat__crep of pat__crep
  | `Pat__csplit of pat__csplit
  | `Pat__eq of pat__eq
  | `Pat__ge of pat__ge
  | `Pat__gt of pat__gt
  | `Pat__iconts of pat__iconts
  | `Pat__ieq of pat__ieq
  | `Pat__ige of pat__ige
  | `Pat__igt of pat__igt
  | `Pat__ile of pat__ile
  | `Pat__ilike of pat__ilike
  | `Pat__ilt of pat__ilt
  | `Pat__imatch of pat__imatch
  | `Pat__in of pat__in
  | `Pat__ine of pat__ine
  | `Pat__inotcs of pat__inotcs
  | `Pat__inot of pat__inot
  | `Pat__inot_ of pat__inot_
  | `Pat__irep of pat__irep
  | `Pat__is of pat__is
  | `Pat__isnot of pat__isnot
  | `Pat__isplit of pat__isplit
  | `Pat__join of pat__join
  | `Pat__le of pat__le
  | `Pat__like of pat__like
  | `Pat__lt of pat__lt
  | `Pat__match of pat__match
  | `Pat__ne of pat__ne
  | `Pat__notcos of pat__notcos
  | `Pat__notin of pat__notin
  | `Pat__notl of pat__notl
  | `Pat__notm of pat__notm
  | `Pat__repl of pat__repl
  | `Pat__shl of pat__shl
  | `Pat__shr of pat__shr
  | `Pat__split of pat__split
]

type verbatim_command_argument = (
    Token.t (* "--%" *) * verbatim_command_argument_chars
)

type generic_type_name = (type_name * Token.t (* "[" *))

type array_type_name = (type_name * Token.t (* "[" *))

type enum_member = (
    simple_name (*tok*)
  * (Token.t (* "=" *) * integer_literal) option
)

type path_command_name =
  [
      `Path_cmd_name_tok of path_command_name_token (*tok*)
    | `Var of variable
  ]
    list (* one or more *)

type switch_parameters = switch_parameter list (* one or more *)

type attribute_name = type_spec

and generic_type_arguments = (
    attribute_name
  * (Token.t (* "," *) * attribute_name) list (* zero or more *)
)

and type_spec = [
    `Array_type_name_opt_dime_RBRACK of (
        array_type_name
      * dimension option
      * Token.t (* "]" *)
    )
  | `Gene_type_name_gene_type_args_RBRACK of (
        generic_type_name * generic_type_arguments * Token.t (* "]" *)
    )
  | `Type_name of type_name
]

type enum_statement = (
    tok_prec_p1_pat_enum (*tok*)
  * simple_name (*tok*)
  * Token.t (* "{" *)
  * (
        enum_member
      * statement_terminator (*tok*)
      * Token.t (* ";" *) list (* zero or more *)
    )
      list (* zero or more *)
  * Token.t (* "}" *)
)

type type_literal = (Token.t (* "[" *) * attribute_name * Token.t (* "]" *))

type catch_type_list = (
    type_literal
  * (Token.t (* "," *) * type_literal) list (* zero or more *)
)

type class_method_parameter = (type_literal option * variable)

type class_method_parameter_list = (
    class_method_parameter
  * (Token.t (* "," *) * class_method_parameter) list (* zero or more *)
)

type additive_argument_expression = [
    `Mult_arg_exp of multiplicative_argument_expression
  | `Addi_arg_exp_choice_PLUS_mult_arg_exp of (
        additive_argument_expression * anon_choice_PLUS_da42005
      * multiplicative_argument_expression
    )
]

and additive_expression = [
    `Mult_exp of multiplicative_expression
  | `Addi_exp_choice_PLUS_mult_exp of (
        additive_expression * anon_choice_PLUS_da42005
      * multiplicative_expression
    )
]

and argument_expression = logical_argument_expression

and argument_expression_list = (
    argument_expression
  * (Token.t (* "," *) * argument_expression) list (* zero or more *)
)

and argument_list = (
    Token.t (* "(" *)
  * argument_expression_list option
  * Token.t (* ")" *)
)

and array_literal_expression = (
    unary_expression
  * (Token.t (* "," *) * unary_expression) list (* zero or more *)
)

and attribute = [
    `LBRACK_attr_name_LPAR_opt_attr_args_RPAR_RBRACK of (
        Token.t (* "[" *)
      * attribute_name
      * Token.t (* "(" *)
      * attribute_arguments option
      * Token.t (* ")" *)
      * Token.t (* "]" *)
    )
  | `Type_lit of type_literal
]

and attribute_argument = [
    `Exp of left_assignment_expression
  | `Simple_name_opt_EQ_exp of (
        simple_name (*tok*)
      * script_parameter_default option
    )
]

and attribute_arguments = (
    attribute_argument
  * (Token.t (* "," *) * attribute_argument) list (* zero or more *)
)

and attribute_list = attribute list (* one or more *)

and bitwise_argument_expression = [
    `Comp_arg_exp of comparison_argument_expression
  | `Bitw_arg_exp_choice_pat__and_comp_arg_exp of (
        bitwise_argument_expression * anon_choice_pat__and_bad5cfe
      * comparison_argument_expression
    )
]

and bitwise_expression = [
    `Comp_exp of comparison_expression
  | `Bitw_exp_choice_pat__band_comp_exp of (
        bitwise_expression
      * [
            `Pat__band of pat__band
          | `Pat__bor of pat__bor
          | `Pat__bxor of pat__bxor
        ]
      * comparison_expression
    )
]

and catch_clause = (pat_catch * catch_type_list option * statement_block)

and catch_clauses = catch_clause list (* one or more *)

and class_method_definition = (
    attribute option
  * class_attribute list (* zero or more *)
  * type_literal option
  * simple_name (*tok*)
  * Token.t (* "(" *)
  * class_method_parameter_list option
  * Token.t (* ")" *)
  * Token.t (* "{" *)
  * script_block option
  * Token.t (* "}" *)
)

and class_property_definition = (
    attribute option
  * class_attribute list (* zero or more *)
  * type_literal option
  * variable
  * script_parameter_default option
)

and class_statement = (
    tok_prec_p1_pat_class (*tok*)
  * simple_name (*tok*)
  * (
        Token.t (* ":" *)
      * simple_name (*tok*)
      * (Token.t (* "," *) * simple_name (*tok*)) list (* zero or more *)
    )
      option
  * Token.t (* "{" *)
  * [
        `Class_prop_defi_stmt_term_rep_SEMI of (
            class_property_definition
          * statement_terminator (*tok*)
          * Token.t (* ";" *) list (* zero or more *)
        )
      | `Class_meth_defi of class_method_definition
    ]
      list (* zero or more *)
  * Token.t (* "}" *)
)

and command = [
    `Cmd_name_opt_cmd_elemes of (command_name * command_elements option)
  | `Cmd_invo_op_cmd_name_expr_opt_cmd_elemes of (
        command_invokation_operator
      * data_command
      * command_elements option
    )
]

and command_argument = [
    `Cmd_arg_sep_opt_gene_tok of (
        command_argument_sep
      * generic_token (*tok*) option
    )
  | `Cmd_arg_sep_array_lit_exp of (
        command_argument_sep * array_literal_expression
    )
  | `Paren_exp of parenthesized_expression
  | `Script_blk_exp of script_block_expression
]

and command_element = [
    `Choice_cmd_param of [
        `Cmd_param of command_parameter (*tok*)
      | `Cmd_arg_opt_arg_list of (command_argument * argument_list option)
      | `Redi of redirection
      | `Stop_pars of stop_parsing (*tok*)
    ]
  | `Semg_ellips of Token.t (* "..." *)
]

and command_elements = command_element list (* one or more *)

and command_name = (
    [
        `Pat_8310886 of pat_8310886
      | `Pat_brk_ of pat_brk_
      | `Pat_cont_ of pat_cont_
      | `Pat_throw_ of pat_throw_
      | `Pat_ret_ of pat_ret_
      | `Pat_exit_ of pat_exit_
      | `Pat_try_ of pat_try_
      | `Pat_trap_ of pat_trap_
      | `Pat_if_ of pat_if_
      | `Pat_func_ of pat_func_
      | `Pat_filter_ of pat_filter_
      | `Pat_work_ of pat_work_
      | `Pat_class_ of pat_class_
      | `Pat_enum_ of pat_enum_
      | `Pat_switch_ of pat_switch_
      | `Pat_for_ of pat_for_
      | `Pat_while_ of pat_while_
      | `Pat_para_ of pat_para_
    ]
  * [
        `Imm_tok_pat_0c51e85 of imm_tok_pat_0c51e85
      | `Imm_tok_dquot_expa_str_lit_imme of (
            imm_tok_dquot (*tok*) * expandable_string_literal_immediate
        )
      | `Imm_tok_dquo of imm_tok_dquotdquot (*tok*)
      | `Imm_tok_squo of imm_tok_squotsquot (*tok*)
    ]
      list (* zero or more *)
)

and command_name_expr = [
    `Cmd_name of command_name
  | `Path_cmd_name of path_command_name
  | `Prim_exp of primary_expression
]

and comparison_argument_expression = [
    `Addi_arg_exp of additive_argument_expression
  | `Comp_arg_exp_comp_op_addi_arg_exp of (
        comparison_argument_expression * comparison_operator
      * additive_argument_expression
    )
]

and comparison_expression = [
    `Addi_exp of additive_expression
  | `Comp_exp_comp_op_addi_exp of (
        comparison_expression * comparison_operator * additive_expression
    )
]

and data_command = command_name_expr

and data_commands_allowed = (pat__supp * data_commands_list)

and data_commands_list = (
    data_command
  * (Token.t (* "," *) * data_command) list (* zero or more *)
)

and data_statement = (
    pat_data
  * simple_name (*tok*) option
  * data_commands_allowed option
  * statement_block
)

and else_clause = (pat_else * statement_block)

and elseif_clause = (
    pat_elseif * Token.t (* "(" *) * while_condition * Token.t (* ")" *)
  * statement_block
)

and elseif_clauses = elseif_clause list (* one or more *)

and expandable_string_literal_immediate = (
    [
        `Pat_a8fb427 of pat_a8fb427
      | `Var of variable
      | `Pat_75780b9 of pat_75780b9
      | `Pat_8a0ae06 of pat_8a0ae06
      | `DQUOTDQUOT of Token.t (* "\"\"" *)
      | `Sub_exp of sub_expression
    ]
      list (* zero or more *)
  * Token.t (* "$" *) list (* zero or more *)
  * Token.t (* "\"" *)
)

and expression = [
    `Logi_exp of logical_expression
  | `Semg_ellips of Token.t (* "..." *)
  | `Semg_deep_ellips of (
        Token.t (* "<..." *) * left_assignment_expression
      * Token.t (* "...>" *)
    )
]

and expression_with_unary_operator = [
    `COMMA_un_exp of (Token.t (* "," *) * unary_expression)
  | `Pat__not_un_exp of (pat__not * unary_expression)
  | `BANG_un_exp of (Token.t (* "!" *) * unary_expression)
  | `Pat__bnot_un_exp of (pat__bnot * unary_expression)
  | `PLUS_un_exp of (Token.t (* "+" *) * unary_expression)
  | `DASH_un_exp of (Token.t (* "-" *) * unary_expression)
  | `Pre_incr_exp of (Token.t (* "++" *) * unary_expression)
  | `Pre_decr_exp of (Token.t (* "--" *) * unary_expression)
  | `Cast_exp of (type_literal * unary_expression)
  | `Pat__split_un_exp of (pat__split * unary_expression)
  | `Pat__join_un_exp of (pat__join * unary_expression)
]

and finally_clause = (pat_fina * statement_block)

and flow_control_statement = [
    `Pat_brk_opt_label_exp of (pat_brk * label_expression option)
  | `Pat_cont_opt_label_exp of (pat_cont * label_expression option)
  | `Pat_throw_opt_pipe of (pat_throw * while_condition option)
  | `Pat_ret_opt_pipe of (pat_ret * while_condition option)
  | `Pat_exit_opt_pipe of (pat_exit * while_condition option)
]

and for_condition = pipeline

and for_initializer = pipeline

and for_iterator = pipeline

and format_argument_expression = [
    `Range_arg_exp of range_argument_expression
  | `Format_arg_exp_format_op_range_arg_exp of (
        format_argument_expression * format_operator
      * range_argument_expression
    )
]

and format_expression = [
    `Range_exp of range_expression
  | `Format_exp_format_op_range_exp of (
        format_expression * format_operator * range_expression
    )
]

and function_parameter_declaration = (
    Token.t (* "(" *)
  * parameter_list option
  * Token.t (* ")" *)
)

and function_statement = (
    [
        `Pat_func of pat_func
      | `Pat_filter of pat_filter
      | `Pat_work of pat_work
    ]
  * command_token (*tok*)
  * function_parameter_declaration option
  * Token.t (* "{" *)
  * script_block option
  * Token.t (* "}" *)
)

and hash_entry = (
    key_expression
  * Token.t (* "=" *)
  * statement
  * statement_terminator (*tok*)
  * Token.t (* ";" *) list (* zero or more *)
)

and hash_literal_body = hash_entry list (* one or more *)

and if_statement = (
    pat_if
  * Token.t (* "(" *)
  * while_condition
  * Token.t (* ")" *)
  * statement_block
  * elseif_clauses option
  * else_clause option
)

and inlinescript_statement = (pat_inli * statement_block)

and invokation_expression = [
    `Prim_exp_imm_tok_dot_member_name_arg_list of (
        primary_expression * imm_tok_dot (*tok*) * member_name
      * argument_list
    )
  | `Prim_exp_COLONCOLON_member_name_arg_list of (
        primary_expression * Token.t (* "::" *) * member_name * argument_list
    )
  | `Invo_fore_exp of (
        primary_expression * imm_tok_prec_p1_pat_5b7d8c6
      * script_block_expression
    )
]

and key_expression = [
    `Simple_name of simple_name (*tok*)
  | `Un_exp of unary_expression
]

and label_expression = [
    `Label of label (*tok*)
  | `Un_exp of unary_expression
]

and labeled_statement = [
    `Switch_stmt of (
        pat_switch
      * switch_parameters option
      * switch_condition
      * switch_body
    )
  | `Fore_stmt of (
        pat_fore
      * foreach_parameter option
      * Token.t (* "(" *)
      * variable
      * pat_in
      * while_condition
      * Token.t (* ")" *)
      * statement_block
    )
  | `For_stmt of (
        pat_for
      * Token.t (* "(" *)
      * (
            (for_initializer * statement_terminator (*tok*)) option
          * (
                anon_choice_SEMI_fddb21e
              * (for_condition * statement_terminator (*tok*)) option
              * (
                    anon_choice_SEMI_fddb21e
                  * (for_iterator * statement_terminator (*tok*)) option
                )
                  option
            )
              option
        )
          option
      * Token.t (* ")" *)
      * statement_block
    )
  | `While_stmt of (
        pat_while * Token.t (* "(" *) * while_condition * Token.t (* ")" *)
      * statement_block
    )
  | `Do_stmt of (
        pat_do
      * statement_block
      * [ `Pat_while of pat_while | `Pat_until of pat_until ]
      * Token.t (* "(" *)
      * while_condition
      * Token.t (* ")" *)
    )
]

and left_assignment_expression = expression

and literal = [
    `Int_lit of integer_literal
  | `Str_lit of string_literal
  | `Real_lit of real_literal (*tok*)
]

and logical_argument_expression = [
    `Bitw_arg_exp of bitwise_argument_expression
  | `Logi_arg_exp_choice_pat__and_bitw_arg_exp of (
        argument_expression * anon_choice_pat__and_bad5cfe
      * bitwise_argument_expression
    )
]

and logical_expression = [
    `Bitw_exp of bitwise_expression
  | `Logi_exp_choice_pat__and_bitw_exp of (
        logical_expression * anon_choice_pat__and_bad5cfe
      * bitwise_expression
    )
]

and member_access = [
    `Prim_exp_imm_tok_dot_member_name of (
        primary_expression * imm_tok_dot (*tok*) * member_name
    )
  | `Prim_exp_COLONCOLON_member_name of (
        primary_expression * Token.t (* "::" *) * member_name
    )
]

and member_name = [
    `Simple_name of simple_name (*tok*)
  | `Str_lit of string_literal
  | `Exp_with_un_op of expression_with_unary_operator
  | `Value of value
]

and multiplicative_argument_expression = [
    `Format_arg_exp of format_argument_expression
  | `Mult_arg_exp_choice_SLASH_format_arg_exp of (
        multiplicative_argument_expression * anon_choice_SLASH_4ca1f7c
      * format_argument_expression
    )
]

and multiplicative_expression = [
    `Format_exp of format_expression
  | `Mult_exp_choice_SLASH_format_exp of (
        multiplicative_expression * anon_choice_SLASH_4ca1f7c
      * format_expression
    )
]

and named_block = (block_name * statement_block)

and named_block_list = named_block list (* one or more *)

and parallel_statement = (pat_para * statement_block)

and param_block = (
    attribute_list option
  * pat_param
  * Token.t (* "(" *)
  * parameter_list option
  * Token.t (* ")" *)
)

and parameter_list = (
    script_parameter
  * (Token.t (* "," *) * script_parameter) list (* zero or more *)
)

and parenthesized_expression = (
    Token.t (* "(" *) * while_condition * Token.t (* ")" *)
)

and pipeline = [
    `Assign_exp of (
        left_assignment_expression * assignement_operator * statement
    )
  | `Pipe_chain_rep_pipe_chain_tail_pipe_chain of (
        pipeline_chain
      * (pipeline_chain_tail * pipeline_chain) list (* zero or more *)
    )
]

and pipeline_chain = [
    `Exp_opt_redirs_opt_pipe_tail of (
        left_assignment_expression
      * redirections option
      * pipeline_tail option
    )
  | `Cmd_opt_verb_cmd_arg_opt_pipe_tail of (
        command
      * verbatim_command_argument option
      * pipeline_tail option
    )
]

and pipeline_tail = (Token.t (* "|" *) * command) list (* one or more *)

and primary_expression = [
    `Value of value
  | `Member_access of member_access
  | `Elem_access of (
        primary_expression * Token.t (* "[" *) * left_assignment_expression
      * Token.t (* "]" *)
    )
  | `Invo_exp of invokation_expression
  | `Post_incr_exp of (primary_expression * Token.t (* "++" *))
  | `Post_decr_exp of (primary_expression * Token.t (* "--" *))
]

and range_argument_expression = [
    `Un_exp of unary_expression
  | `Range_arg_exp_DOTDOT_un_exp of (
        range_argument_expression * Token.t (* ".." *) * unary_expression
    )
]

and range_expression = [
    `Array_lit_exp of array_literal_expression
  | `Range_exp_DOTDOT_array_lit_exp of (
        range_expression * Token.t (* ".." *) * array_literal_expression
    )
]

and redirected_file_name = [
    `Cmd_arg of command_argument
  | `Prim_exp of primary_expression
]

and redirection = [
    `Merg_redi_op of merging_redirection_operator
  | `File_redi_op_redi_file_name of (
        file_redirection_operator * redirected_file_name
    )
]

and redirections = redirection list (* one or more *)

and script_block = [
    `Script_blk_body of script_block_body
  | `Param_blk_stmt_term_rep_SEMI_opt_script_blk_body of (
        param_block
      * statement_terminator (*tok*)
      * Token.t (* ";" *) list (* zero or more *)
      * script_block_body option
    )
]

and script_block_body = [
    `Named_blk_list of named_block_list
  | `Stmt_list of statement_list
]

and script_block_expression = (
    Token.t (* "{" *)
  * param_block option
  * script_block
  * Token.t (* "}" *)
)

and script_parameter = (
    attribute_list option
  * variable
  * script_parameter_default option
)

and script_parameter_default = (
    Token.t (* "=" *) * left_assignment_expression
)

and sequence_statement = (pat_seq * statement_block)

and statement = [
    `Choice_if_stmt of [
        `If_stmt of if_statement
      | `Opt_label_labe_stmt of (label (*tok*) option * labeled_statement)
      | `Func_stmt of function_statement
      | `Class_stmt of class_statement
      | `Enum_stmt of enum_statement
      | `Flow_cont_stmt_stmt_term of (
            flow_control_statement * statement_terminator (*tok*)
        )
      | `Trap_stmt of trap_statement
      | `Try_stmt of try_statement
      | `Data_stmt of data_statement
      | `Inli_stmt of inlinescript_statement
      | `Para_stmt of parallel_statement
      | `Seq_stmt of sequence_statement
      | `Pipe_stmt_term of (while_condition * statement_terminator (*tok*))
      | `Empty_stmt of Token.t (* ";" *)
    ]
  | `Semg_ellips of Token.t (* "..." *)
]

and statement_block = (
    Token.t (* "{" *)
  * statement_list option
  * Token.t (* "}" *)
)

and statement_list = statement list (* one or more *)

and string_literal = [
    `Expa_str_lit of (
        pat_0f43aa8
      * [
            `Imm_tok_pat_46ba992 of imm_tok_pat_46ba992
          | `Var of variable
          | `Sub_exp of sub_expression
          | `Imm_tok_pat_f92c05a of imm_tok_pat_f92c05a
          | `Imm_tok_pat_8a0ae06 of imm_tok_pat_8a0ae06
          | `Imm_tok_dquo of imm_tok_dquotdquot (*tok*)
          | `Imm_tok_dollar of imm_tok_dollar (*tok*)
        ]
          list (* zero or more *)
      * imm_tok_dollar (*tok*) list (* zero or more *)
      * imm_tok_pat_0da7e88
    )
  | `Verb_str_charas of verbatim_string_characters (*tok*)
  | `Expa_here_str_lit of (
        pat_60937fc
      * [
            `Imm_tok_pat_b45f689 of imm_tok_pat_b45f689
          | `Var of variable
          | `Sub_exp of sub_expression
          | `Imm_tok_pat_883ef26 of imm_tok_pat_883ef26
          | `Imm_tok_pat_0f818ff of imm_tok_pat_0f818ff
          | `Imm_tok_dollar of imm_tok_dollar (*tok*)
          | `Imm_tok_pat_8a0ae06 of imm_tok_pat_8a0ae06
        ]
          list (* zero or more *)
      * imm_tok_pat_3dc846d
    )
  | `Verb_here_str_charas of verbatim_here_string_characters (*tok*)
]

and sub_expression = (
    Token.t (* "$(" *)
  * statement_list option
  * Token.t (* ")" *)
)

and switch_body = (
    Token.t (* "{" *)
  * switch_clauses option
  * Token.t (* "}" *)
)

and switch_clause = (
    switch_clause_condition
  * statement_block
  * statement_terminator (*tok*)
  * Token.t (* ";" *) list (* zero or more *)
)

and switch_clause_condition = [
    `Cmd_tok of command_token (*tok*)
  | `Prim_exp of primary_expression
]

and switch_clauses = switch_clause list (* one or more *)

and switch_condition = [
    `LPAR_pipe_RPAR of parenthesized_expression
  | `Pat__file_switch_file of (pat__file * switch_filename)
]

and switch_filename = [
    `Cmd_tok of command_token (*tok*)
  | `Prim_exp of primary_expression
]

and trap_statement = (pat_trap * type_literal option * statement_block)

and try_statement = (
    pat_try
  * statement_block
  * [
        `Catch_clauses_opt_fina_clause of (
            catch_clauses
          * finally_clause option
        )
      | `Opt_fina_clause of finally_clause option
    ]
)

and unary_expression = [
    `Prim_exp of primary_expression
  | `Exp_with_un_op of expression_with_unary_operator
]

and value = [
    `Paren_exp of parenthesized_expression
  | `Sub_exp of sub_expression
  | `Array_exp of (
        Token.t (* "@(" *)
      * statement_list option
      * Token.t (* ")" *)
    )
  | `Script_blk_exp of script_block_expression
  | `Hash_lit_exp of (
        Token.t (* "@{" *)
      * hash_literal_body option
      * Token.t (* "}" *)
    )
  | `Lit of literal
  | `Type_lit of type_literal
  | `Var of variable
]

and while_condition = pipeline

type program = (param_block option * statement_list)

type empty_statement (* inlined *) = Token.t (* ";" *)

type semgrep_ellipsis (* inlined *) = Token.t (* "..." *)

type comment (* inlined *) = Token.t

type data_name (* inlined *) = simple_name (*tok*)

type function_name (* inlined *) = command_token (*tok*)

type attributed_variable (* inlined *) = (type_literal * variable)

type array_expression (* inlined *) = (
    Token.t (* "@(" *)
  * statement_list option
  * Token.t (* ")" *)
)

type assignment_expression (* inlined *) = (
    left_assignment_expression * assignement_operator * statement
)

type cast_expression (* inlined *) = (type_literal * unary_expression)

type do_statement (* inlined *) = (
    pat_do
  * statement_block
  * [ `Pat_while of pat_while | `Pat_until of pat_until ]
  * Token.t (* "(" *)
  * while_condition
  * Token.t (* ")" *)
)

type element_access (* inlined *) = (
    primary_expression * Token.t (* "[" *) * left_assignment_expression
  * Token.t (* "]" *)
)

type expandable_here_string_literal (* inlined *) = (
    pat_60937fc
  * [
        `Imm_tok_pat_b45f689 of imm_tok_pat_b45f689
      | `Var of variable
      | `Sub_exp of sub_expression
      | `Imm_tok_pat_883ef26 of imm_tok_pat_883ef26
      | `Imm_tok_pat_0f818ff of imm_tok_pat_0f818ff
      | `Imm_tok_dollar of imm_tok_dollar (*tok*)
      | `Imm_tok_pat_8a0ae06 of imm_tok_pat_8a0ae06
    ]
      list (* zero or more *)
  * imm_tok_pat_3dc846d
)

type expandable_string_literal (* inlined *) = (
    pat_0f43aa8
  * [
        `Imm_tok_pat_46ba992 of imm_tok_pat_46ba992
      | `Var of variable
      | `Sub_exp of sub_expression
      | `Imm_tok_pat_f92c05a of imm_tok_pat_f92c05a
      | `Imm_tok_pat_8a0ae06 of imm_tok_pat_8a0ae06
      | `Imm_tok_dquo of imm_tok_dquotdquot (*tok*)
      | `Imm_tok_dollar of imm_tok_dollar (*tok*)
    ]
      list (* zero or more *)
  * imm_tok_dollar (*tok*) list (* zero or more *)
  * imm_tok_pat_0da7e88
)

type for_statement (* inlined *) = (
    pat_for
  * Token.t (* "(" *)
  * (
        (for_initializer * statement_terminator (*tok*)) option
      * (
            anon_choice_SEMI_fddb21e
          * (for_condition * statement_terminator (*tok*)) option
          * (
                anon_choice_SEMI_fddb21e
              * (for_iterator * statement_terminator (*tok*)) option
            )
              option
        )
          option
    )
      option
  * Token.t (* ")" *)
  * statement_block
)

type foreach_statement (* inlined *) = (
    pat_fore
  * foreach_parameter option
  * Token.t (* "(" *)
  * variable
  * pat_in
  * while_condition
  * Token.t (* ")" *)
  * statement_block
)

type hash_literal_expression (* inlined *) = (
    Token.t (* "@{" *)
  * hash_literal_body option
  * Token.t (* "}" *)
)

type invokation_foreach_expression (* inlined *) = (
    primary_expression * imm_tok_prec_p1_pat_5b7d8c6
  * script_block_expression
)

type post_decrement_expression (* inlined *) = (
    primary_expression * Token.t (* "--" *)
)

type post_increment_expression (* inlined *) = (
    primary_expression * Token.t (* "++" *)
)

type pre_decrement_expression (* inlined *) = (
    Token.t (* "--" *) * unary_expression
)

type pre_increment_expression (* inlined *) = (
    Token.t (* "++" *) * unary_expression
)

type semgrep_deep_ellipsis (* inlined *) = (
    Token.t (* "<..." *) * left_assignment_expression * Token.t (* "...>" *)
)

type switch_statement (* inlined *) = (
    pat_switch
  * switch_parameters option
  * switch_condition
  * switch_body
)

type while_statement (* inlined *) = (
    pat_while * Token.t (* "(" *) * while_condition * Token.t (* ")" *)
  * statement_block
)

type extra = [ `Comment of Loc.t * comment ]

type extras = extra list
